---
# handlers file for postgresql
- name: set db password
  become_user: "{{ pg_superuser }}"
  community.postgresql.postgresql_user:
    name: "{{ pg_superuser }}"
    password: "{{ pg_password }}"
    role_attr_flags: 'SUPERUSER'
    state: present

- name: restart db service
  ansible.builtin.systemd:
    name: "{{ svc_db }}"
    state: restarted
